# import the relevant libraries

In [2]:
import numpy as np

# Addition

In [3]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [4]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [5]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

# Difference

In [6]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

# Error

In [7]:
j1 = np.array([2,5])

if row and column of a mtrices or vector are not the same then we get error while doing add or sub operations

In [10]:
m1+j1

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [11]:
m1-j1

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

# Exceptions (addition with scaler)

In [14]:
m1 + 1 #same for vector
#its an exception only in the case of programming because shapes are different
#No meaning in terms of algebra

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [16]:
m1 + np.array([1]) 
#it shows meaning both in mathematical and programming

array([[ 6, 13,  7],
       [-2,  1, 15]])

# Transpose

In [17]:
m1.T #transposing m1

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [19]:
s = np.array([5])
s

array([5])

In [20]:
s.T #transposing scaler

array([5])

In [23]:
v1 = np.array([1,2,3]) 

In [24]:
v1.T

array([1, 2, 3])

In [25]:
v1.shape

(3,)

In [30]:
v1_reshaped = v1.reshape(1,3)
v1_reshaped
v1_reshaped.T #transposing vectors

array([[1],
       [2],
       [3]])