In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.linear_model import LinearRegression

In [29]:
data = pd.read_csv('1.02. Multiple linear regression(1).csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

Assign Feature and Output

In [30]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

# Standardization

In [31]:
from sklearn.preprocessing import StandardScaler # Used for standarization
scaler = StandardScaler()
scaler.fit(x)
x_scaled = scaler.transform(x)  
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

# Regression with Scaled Feature

In [32]:
reg = LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [33]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [34]:
reg.intercept_

3.330238095238095

# Creating summary table

In [35]:
reg_summary = pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']], columns= ['Features'])        
reg_summary['Weights'] = reg.intercept_,reg.coef_[0],reg.coef_[1]                          
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

# Making Prediction with Standardized Coefficients

In [36]:
new_data = pd.DataFrame(data = [[1760,3],[1685,3]], columns= ['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1760           3
1  1685           3

In [37]:
reg.predict(new_data) # as we didn't use scaled x (i.e SAT) predictor doesn't normalize

array([305.70159913, 292.81555717])

Now using feature selection through standardization (normalization)

In [38]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974]])

In [39]:
reg.predict(new_data_scaled)

array([3.18145672, 3.05744108])

# What if we remove 'Rand 1,2,3' 

In [40]:
reg_simple = LinearRegression()
x_scaled_matrix = x_scaled[ : ,0].reshape(-1,1)
x_scaled_matrix

array([[-1.26338288],
       [-1.74458431],
       [-0.82067757],
       [-1.54247971],
       [-1.46548748],
       [-1.68684014],
       [-0.78218146],
       [-0.78218146],
       [-0.51270866],
       [ 0.04548499],
       [-1.06127829],
       [-0.67631715],
       [-1.06127829],
       [-1.28263094],
       [-0.6955652 ],
       [ 0.25721362],
       [-0.86879772],
       [-1.64834403],
       [-0.03150724],
       [-0.57045283],
       [-0.81105355],
       [-1.18639066],
       [-1.75420834],
       [-1.52323165],
       [ 1.23886453],
       [-0.18549169],
       [-0.5608288 ],
       [-0.23361183],
       [ 1.68156984],
       [-0.4934606 ],
       [-0.73406132],
       [ 0.85390339],
       [-0.67631715],
       [ 0.09360513],
       [ 0.33420585],
       [ 0.03586096],
       [-0.35872421],
       [ 1.04638396],
       [-0.65706909],
       [-0.13737155],
       [ 0.18984542],
       [ 0.04548499],
       [ 1.1618723 ],
       [-1.37887123],
       [ 1.39284898],
       [ 0

In [41]:
reg_simple.fit(x_scaled_matrix,y)

LinearRegression()

In [45]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.18905127, 3.06487466])

Which shows there are no impact on 'Rand 1,2,3' on the multiple regression line.....